const H = require("./helpers");
const { h1, h2, h3, p, lead, bullet, num, kpi, spacer, pageBreak, source, figcap, table, hbar, callout } = H;

// ===================== SECTION 1: MARKET ANALYSIS =====================
function section1() {
  return [
    new H.docx.Paragraph({ pageBreakBefore: true, heading: H.docx.HeadingLevel.HEADING_1, children: [H.t("1. Market Analysis")] }),
    lead("The macro opportunity: six overlapping markets — AI, IT services, AI consulting, automation, digital transformation and SaaS — that together exceed USD 8 trillion in annual technology spend and are compounding at double digits through 2035."),

    p("The division you are launching sits at the intersection of six large, fast-growing markets. They overlap heavily — an “AI agent” engagement is simultaneously AI, IT services, automation and digital transformation — which is strategically important: a single client relationship can be monetised across multiple budget lines. The figures below are drawn from the leading research houses (Gartner, IDC, NASSCOM-BCG, Grand View, Precedence, MarketsandMarkets, Statista). Estimates vary widely by methodology and scope, so we present ranges and cite the basis of each headline number [refs 1–12]."),

    h2("1.1 The Six Markets at a Glance"),
    table([2180, 1500, 1500, 1400, 2780],
      [
        ["Market", "2024–25 Size", "2030–35 Proj.", "CAGR", "Primary Source Basis"],
        ["AI (total market)", "$224–758 B", "$1.2–4.2 T", "19–33%", "Precedence; NextMSC; market.us [1,2]"],
        ["AI-as-a-Service (AIaaS)", "$16.1 B", "$105 B (2030)", "36.1%", "Grand View Research [3]"],
        ["Generative AI", "$22–104 B", "$325–990 B", "29–43%", "Grand View; GMI; Fortune BI [4]"],
        [{ text: "IT Services", bold: true }, "$1.6–1.9 T", "$3.2–4.7 T", "7–10%", "Precedence; Grand View; Gartner [5,6]"],
        ["AI Consulting", "$8.8–22 B", "$91–258 B", "26–36%", "Future Market Insights; BRI [7,8]"],
        ["RPA", "$11–28 B", "$132–247 B", "24–36%", "Precedence; SkyQuest; Technavio [9]"],
        ["Hyperautomation", "$16–66 B", "$38–306 B", "17–20%", "Precedence; Mordor [9]"],
        ["Digital Transformation", "$1.07–1.5 T", "$4.6–5.0 T", "18–28%", "Grand View; TBRC [10,11]"],
        ["SaaS", "$399–408 B", "$774 B–1.37 T", "12–22%", "Grand View; Precedence; Technavio [12]"],
      ],
      { fontSize: 17 }),
    figcap("Figure 1. Market-sizing summary. Ranges reflect divergent analyst scope; mid-points used for planning."),

    h2("1.2 Market Size — Relative Scale (2024–25)"),
    p("To plan capital and hiring, what matters is relative scale and growth, not a single contested number. IT services is the cash-flow ocean; AI and digital transformation are the fast-rising tides; AIaaS, GenAI and AI consulting are small today but the steepest-growing pools — precisely where a new, AI-first entrant can win disproportionate share."),
    hbar([
      { label: "IT Services", value: 1750, display: "~$1.75 T" },
      { label: "Digital Transf.", value: 1200, display: "~$1.2 T" },
      { label: "AI (total)", value: 500, display: "~$500 B" },
      { label: "SaaS", value: 400, display: "~$400 B" },
      { label: "Hyperautomation", value: 66, display: "~$66 B" },
      { label: "RPA", value: 28, display: "~$28 B" },
      { label: "GenAI", value: 60, display: "~$60 B" },
      { label: "AIaaS", value: 16, display: "~$16 B" },
      { label: "AI Consulting", value: 15, display: "~$15 B" },
    ], { maxVal: 1750 }),
    figcap("Figure 2. Approximate 2024–25 market size (USD, log-feel scale). Source: composite of refs 1–12."),

    h2("1.3 Growth Rates — Where the Momentum Is"),
    p("The new division should over-index toward the high-CAGR pools while using IT-services demand as the entry door. The order below is the order in which value is migrating."),
    hbar([
      { label: "Generative AI", value: 43, display: "29–43%", color: H.GREEN },
      { label: "AIaaS", value: 36, display: "~36%", color: H.GREEN },
      { label: "RPA", value: 35, display: "24–36%", color: H.GREEN },
      { label: "AI (total)", value: 33, display: "19–33%", color: H.BLUE },
      { label: "AI Consulting", value: 30, display: "26–36%", color: H.BLUE },
      { label: "Digital Transf.", value: 28, display: "18–28%", color: H.BLUE },
      { label: "Hyperautomation", value: 19, display: "17–20%", color: H.AMBER },
      { label: "SaaS", value: 17, display: "12–22%", color: H.AMBER },
      { label: "IT Services", value: 9, display: "7–10%", color: H.AMBER },
    ], { maxVal: 43 }),
    figcap("Figure 3. Upper-bound CAGR by market. Source: refs 1–12."),

    h2("1.4 Future Projections (2025–2035)"),
    p("Across the planning horizon, three things compound simultaneously: (a) AI shifts from pilots to production, (b) automation moves from task-level RPA to agentic, end-to-end process automation, and (c) buyers consolidate vendors toward partners who can do strategy, build and run. The consensus trajectory:"),
    bullet("By 2027: India's domestic AI market alone reaches ~USD 17 B (NASSCOM-BCG); enterprise GenAI crosses from experimentation to budgeted line-items [13]."),
    bullet("By 2030: Digital transformation spend approaches USD 4.6–5.0 T; AIaaS ~USD 105 B; SaaS USD 0.8–1.4 T; AI agents become a distinct, multi-hundred-billion-dollar category."),
    bullet("By 2034–35: Total AI market plausibly USD 1.2–4.2 T; IT services USD 3.2–4.7 T; RPA USD 132–247 B. AI becomes a horizontal layer in essentially every IT and BPO contract."),

    h2("1.5 Demand Trends"),
    bullet([H.t("From pilots to production. ", { bold: true }), H.t("The dominant 2025–2030 theme is operationalising GenAI — moving the ~70–80% of stalled pilots into measurable ROI. Buyers want outcomes, not demos.")]),
    bullet([H.t("Agentic AI. ", { bold: true }), H.t("Autonomous, tool-using AI agents are the fastest-emerging sub-category, projected by Precedence to reach ~USD 295 B by 2035. They subsume chatbots, RPA and workflow automation into one paradigm.")]),
    bullet([H.t("Vendor consolidation + 'outcome' pricing. ", { bold: true }), H.t("CXOs are cutting vendor counts and shifting from time-and-materials to outcome- and consumption-based pricing.")]),
    bullet([H.t("SME / mid-market democratisation. ", { bold: true }), H.t("Cloud + low-code + GenAI have collapsed the cost of automation, opening a vast under-served SME market — acute in India where 63 M MSMEs run on WhatsApp and Excel [14].")]),
    bullet([H.t("Data & governance first. ", { bold: true }), H.t("Buyers increasingly understand that AI value is gated by data readiness, security and governance — creating durable advisory + data-engineering demand.")]),

    h2("1.6 Major Growth Drivers"),
    table([3000, 6360], [
      ["Driver", "Why it expands the market"],
      ["GenAI productivity proof", "Documented 20–50% productivity gains in code, support, marketing and back-office push CFOs from curiosity to budget."],
      ["Labour cost & shortages", "Wage inflation and talent scarcity make automation a board-level cost lever, not an IT experiment."],
      ["Cloud maturity", "Hyperscaler AI services (Azure OpenAI, AWS Bedrock, Google Vertex) remove infra barriers, shrinking time-to-value."],
      ["Digital public infrastructure (India)", "UPI, GST, ONDC, Account Aggregator and DigiLocker create structured data + rails that make automation deployable at SME scale."],
      ["Regulatory & ESG reporting", "Compliance, audit and sustainability reporting create non-discretionary analytics + automation demand."],
      ["Competitive FOMO", "Once a category leader adopts AI, peers must follow — driving fast, sector-by-sector diffusion."],
    ], { fontSize: 17 }),

    h2("1.7 Market Challenges"),
    bullet("Pilot-to-production gap: most GenAI pilots never reach ROI; trust, data quality and change management are the blockers."),
    bullet("Talent scarcity & wage inflation in AI/ML engineering, MLOps and data engineering."),
    bullet("Commoditisation pressure: low-code + foundation models compress the price of 'simple' builds."),
    bullet("Security, privacy, IP and hallucination risk slow enterprise adoption and lengthen sales cycles."),
    bullet("Buyer skepticism after over-hyped 2023–24 pilots; ROI proof is now a precondition, not a nicety."),
    bullet("Regulatory uncertainty (EU AI Act, India DPDP Act 2023, sectoral rules) raises compliance cost."),

    h2("1.8 Technology Trends to Build Around"),
    table([2600, 6760], [
      ["Trend", "Implication for the new division"],
      ["Agentic AI / multi-agent systems", "Build a reusable agent framework (orchestration, tools, guardrails) as core IP and a repeatable offer."],
      ["RAG & enterprise knowledge", "Retrieval-augmented assistants over private data are the #1 'safe' enterprise GenAI entry point."],
      ["Small / open models + fine-tuning", "On-prem / private deployments (Llama, Mistral, fine-tuned SLMs) win regulated and cost-sensitive buyers."],
      ["AI + RPA convergence (IPA)", "Intelligent process automation replaces brittle RPA; position as the upgrade path."],
      ["Vertical AI / domain copilots", "Industry-specific solutions command premium pricing and defend against horizontal commoditisation."],
      ["Vector DBs, MLOps, LLMOps", "Productionising and monitoring AI is a recurring, sticky services line."],
      ["Computer vision & Voice AI", "Manufacturing QC, retail analytics and voice agents open non-chat AI revenue."],
    ], { fontSize: 17 }),

    h2("1.9 Market Gaps & Future Opportunities"),
    callout("Where a focused new entrant can win", [
      "1. The SME / mid-market 'last mile' — affordable, productised AI & automation that the Big-4/SIs ignore because deal sizes are small.",
      "2. Outcome-based, vertical solutions (clinic ops, exporter documentation, factory QC) instead of generic 'AI consulting'.",
      "3. Production & governance — rescuing stalled pilots and running AI in production (MLOps/LLMOps managed services).",
      "4. Tier-2/3 India & cost-sensitive global SMBs — 30–40% lower delivery cost than metros, near-zero incumbent coverage [15].",
      "5. AI-native delivery — using AI internally to deliver faster/cheaper than incumbents whose economics depend on headcount.",
    ]),
    source("Composite of Precedence Research, Grand View Research, MarketsandMarkets, NextMSC, market.us, Future Market Insights, Business Research Insights, Technavio, NASSCOM Strategic Review 2025, NASSCOM-BCG, World Economic Forum, Statista (2024–2026). Full citations in References."),
  ];
}

// ===================== SECTION 2: GLOBAL COMPETITOR ANALYSIS =====================
function section2() {
  return [
    new H.docx.Paragraph({ pageBreakBefore: true, heading: H.docx.HeadingLevel.HEADING_1, children: [H.t("2. Global Competitor Analysis")] }),
    lead("The field splits into three tiers: global giants who own the enterprise, mid-cap specialists who own the analytics/AI niche, and AI-first challengers redefining delivery. A new entrant cannot beat any of them at their own game — it must pick an unguarded edge."),

    p("We profile the competitive set in three tiers. Tier 1 are the global system integrators and consulting firms that dominate enterprise budgets. Tier 2 are mid-sized, often analytics/AI-pure-play specialists. Tier 3 are platforms and AI-first challengers. Financials are latest reported (FY2024–25) and rounded; private-company figures are best-available estimates and flagged accordingly [refs 16–22]."),

    h2("2.1 Competitive Landscape Map"),
    table([1450, 2650, 2650, 2610], [
      ["Tier", "Who they are", "Strength", "Where they're weak (your opening)"],
      [{ text: "Tier 1\nGlobal giants", bold: true, fill: H.LIGHTBLUE }, "Accenture, Deloitte, TCS, Infosys, IBM, Capgemini, Cognizant, PwC, Wipro, HCLTech", "Scale, trust, global delivery, deep enterprise relationships", "Expensive, slow, ignore SMEs, generalist; high min. deal size"],
      [{ text: "Tier 2\nSpecialists", bold: true, fill: H.LIGHTBLUE }, "Fractal, Tiger Analytics, Quantiphi, Thoughtworks, Persistent, LTIMindtree, Nagarro, Tech Mahindra", "Deep AI/data skill, faster, better price-value", "Still enterprise-focused; limited SME productisation"],
      [{ text: "Tier 3\nAI-first / platforms", bold: true, fill: H.LIGHTBLUE }, "Palantir, UiPath, Automation Anywhere, ServiceNow, DataRobot + 1000s of GenAI startups", "Product leverage, cutting-edge, high margin", "Product not service; need partners for last-mile delivery"],
    ], { fontSize: 16 }),

    h2("2.2 Tier 1 — Global Giants (Deep Profiles)"),

    h3("Accenture"),
    table([2400, 6960], [
      ["Field", "Detail"],
      ["HQ / Website", "Dublin, Ireland · accenture.com"],
      ["Revenue / Employees", "~USD 69.7 B (FY2025) · ~799,000 staff [16]"],
      ["Services", "Strategy, consulting, technology, operations, Song (marketing), Industry X; end-to-end digital + AI transformation"],
      ["AI capability", "GenAI new bookings ~USD 5.9 B FY2025; 'reinvention' positioning; massive cloud + data partnerships"],
      ["Pricing / model", "Premium T&M + outcome; multi-year managed services. Enterprise only"],
      ["Strengths", "Unmatched scale, C-suite trust, breadth, delivery muscle"],
      ["Weaknesses", "Very expensive; slow; not built for SME/mid-market; generalist vs niche depth"],
      ["Positioning", "The default 'safe' choice for Fortune 2000 reinvention"],
    ], { fontSize: 16 }),

    h3("TCS, Infosys, Wipro, HCLTech (Indian IT majors)"),
    table([1700, 1450, 1450, 1500, 3260], [
      ["Company", "Revenue", "Employees", "HQ", "Notes"],
      ["TCS", "~$29 B", "~607,000", "Mumbai", "Largest Indian IT; AI deal pipeline building; deep BFSI/retail"],
      ["Infosys", "~$19 B", "~317,000", "Bengaluru", "FY25 ~₹1.37 T; Topaz AI suite; 60%+ digital bookings [16]"],
      ["Wipro", "~$10.5 B", "~233,000", "Bengaluru", "ai360; bookings +51% YoY in a recent quarter [16]"],
      ["HCLTech", "~$13.8 B", "~220,000", "Noida", "Strong engineering/ER&D + AIForce platform"],
    ], { fontSize: 16 }),
    p("Strengths: cost-efficient global delivery, vast talent, sticky enterprise contracts. Weaknesses: linear (headcount-led) economics under pressure from AI, generalist positioning, minimal SME focus, and innovation perceived as following rather than leading. This is the gap an AI-native, productised challenger exploits."),

    h3("Deloitte / PwC / IBM Consulting / Capgemini / Cognizant"),
    table([2050, 7310], [
      ["Firm", "Profile & competitive note"],
      ["Deloitte", "~$67 B revenue, ~460k people. Audit-anchored relationships + fast-growing AI/analytics practice. Premium, governance-led, enterprise."],
      ["PwC", "~$55 B, ~370k. Big bet on GenAI advisory (multi-billion alliance with OpenAI/Microsoft). Strong in regulated industries."],
      ["IBM Consulting", "~$20 B segment. watsonx platform + consulting; hybrid-cloud + AI; strong in regulated, on-prem buyers."],
      ["Capgemini", "~€22 B, ~340k. Strong Europe presence, engineering + 'Resonance' GenAI portfolio."],
      ["Cognizant", "~$19.7 B, ~340k. Healthcare/BFSI heavy; Neuro AI platform; aggressive AI re-skilling."],
    ], { fontSize: 16 }),

    h2("2.3 Tier 2 — Specialists & Mid-Caps"),
    table([1850, 1450, 6060], [
      ["Company", "Scale", "Why they matter / weakness"],
      ["Fractal Analytics", "~$330 M ARR; ~6,700 staff; ~$2.4 B val.; IPO-bound [17]", "India's premier enterprise-AI pure-play; CPG/BFSI. Weakness: thin SME/domestic demand engine [17]."],
      ["Tiger Analytics", "~$300 M+ (est.), ~5,000", "Data + AI consulting, US-centric. Weakness: brand depth vs Fractal."],
      ["Quantiphi", "~$200 M+ (est.), ~4,000", "Applied AI + cloud (Google/AWS partner). Weakness: dependence on hyperscaler alliances."],
      ["LTIMindtree", "~$4.3 B, ~84,000", "Full-service mid-major; BlueVerse GenAI. Weakness: integration + mid-tier positioning."],
      ["Persistent Systems", "~$1.4 B, ~23,000", "Digital engineering + AI; strong growth. Weakness: scale vs majors."],
      ["Thoughtworks", "~$1.1 B, ~10,500", "Premium engineering + AI; agile pedigree. Weakness: high cost, recent margin pressure."],
      ["Nagarro", "~€1 B, ~18,000", "Agile digital engineering, 'fluidic enterprise'. Weakness: lighter brand recognition."],
      ["Tech Mahindra", "~$6.3 B, ~145,000", "Telco/5G + AI (Project Indus LLM). Weakness: margin and turnaround mode."],
      ["Birlasoft / Zensar / Coforge", "~$0.6–1.4 B each", "Mid-cap SIs digitising verticals; vulnerable to AI margin compression."],
    ], { fontSize: 16 }),

    h2("2.4 Tier 3 — AI-First Platforms & Challengers"),
    table([1900, 1500, 5960], [
      ["Company", "Scale", "Model & note"],
      ["Palantir", "~$3.4–4.5 B rev (2025), profitable [18]", "AIP + Foundry ontology/agents; gov + commercial. Product-led, premium; needs SI delivery partners."],
      ["UiPath", "~$1.43 B rev; $1.67 B ARR [18]", "RPA leader pivoting to agentic automation. Partner ecosystem = channel opportunity."],
      ["Automation Anywhere", "~$0.6 B (est., private)", "Cloud-native RPA + GenAI (Automation Co-Pilot). Channel-led."],
      ["ServiceNow", "~$11 B rev", "Workflow platform + Now Assist GenAI; ITSM/ops dominance; huge partner economy."],
      ["DataRobot", "~$0.3 B (est., private)", "Enterprise AI/ML lifecycle platform; pivoting to agentic/GenAI apps."],
      ["GenAI-native startups", "Seed–Series C", "Glean, Cohere, Sierra, Cresta, Writer + 1,000s; redefining UX and price points; potential partners or niche rivals."],
    ], { fontSize: 16 }),

    h2("2.5 What This Means for You"),
    callout("Competitive takeaways", [
      "Incumbents own the enterprise top-down; nobody owns the SME/mid-market bottom-up at scale.",
      "Their economics are headcount-led — an AI-native delivery model can undercut on price and beat on speed.",
      "Platforms (UiPath, ServiceNow, Palantir, hyperscalers) need last-mile delivery partners — your fastest credibility and lead path.",
      "Differentiate on vertical depth + outcomes + productised pricing, never on 'we also do AI'.",
    ]),
    source("Accenture/Wipro/UiPath/Palantir SEC & investor filings (FY2024–25); Crunchbase, GetLatka, Growjo, Inc42, Tradebrains, Forrester (2025); company disclosures. Estimates flagged. Full citations in References."),
  ];
}

// ===================== SECTION 3: INDIAN COMPETITOR ANALYSIS =====================
function section3() {
  const indianFirms = [
    ["Fractal Analytics", "Mumbai", "Enterprise AI/analytics", "fractal.ai"],
    ["Tiger Analytics", "Chennai/CA", "Data & AI consulting", "tigeranalytics.com"],
    ["Quantiphi", "Mumbai", "Applied AI + cloud", "quantiphi.com"],
    ["Mu Sigma", "Bengaluru", "Decision sciences", "mu-sigma.com"],
    ["LatentView Analytics", "Chennai", "Data analytics", "latentview.com"],
    ["Course5 Intelligence", "Mumbai", "Analytics + GenAI", "course5i.com"],
    ["Absolutdata (Infogain)", "Gurugram", "AI/analytics", "absolutdata.com"],
    ["Gramener", "Hyderabad", "Data storytelling/AI", "gramener.com"],
    ["Sigmoid", "Bengaluru", "Data engineering + AI", "sigmoid.com"],
    ["Crayon Data", "Chennai", "AI personalisation", "crayondata.com"],
    ["Yellow.ai", "Bengaluru", "Conversational AI", "yellow.ai"],
    ["Haptik (Jio)", "Mumbai", "Conversational AI", "haptik.ai"],
    ["Uniphore", "Chennai/US", "Voice/conversational AI", "uniphore.com"],
    ["Observe.AI", "Bengaluru", "Contact-centre AI", "observe.ai"],
    ["Senseforth.ai", "Bengaluru", "Conversational AI", "senseforth.ai"],
    ["Vernacular.ai (Skit)", "Bengaluru", "Voice AI", "skit.ai"],
    ["Gupshup", "Bengaluru", "Conversational messaging", "gupshup.io"],
    ["Verloop.io", "Bengaluru", "Support automation", "verloop.io"],
    ["Mad Street Den", "Chennai", "Computer vision/retail AI", "madstreetden.com"],
    ["SigTuple", "Bengaluru", "Medical imaging AI", "sigtuple.com"],
    ["Niramai", "Bengaluru", "Healthcare AI (thermal)", "niramai.com"],
    ["Qure.ai", "Mumbai", "Radiology AI", "qure.ai"],
    ["Innovaccer", "Noida/US", "Healthcare data/AI", "innovaccer.com"],
    ["SquadStack", "Noida", "AI sales/ops", "squadstack.com"],
    ["Locobuzz", "Mumbai", "CX + social AI", "locobuzz.com"],
    ["Manthan/Algonomy", "Bengaluru", "Retail AI", "algonomy.com"],
    ["Vue.ai", "Chennai", "Retail automation AI", "vue.ai"],
    ["Wobot.ai", "Gurugram", "Vision intelligence", "wobot.ai"],
    ["Staqu", "Gurugram", "Video analytics AI", "staqu.com"],
    ["AjnaLens", "Mumbai", "AR + AI training", "ajnalens.com"],
    ["Streamingo / Detect", "Bengaluru", "Vision AI", "detect.ai"],
    ["Cogno AI", "Mumbai", "BFSI conversational AI", "cogno.ai"],
    ["Kenscio / Netcore AI", "Mumbai", "Marketing AI", "netcorecloud.com"],
    ["Zoko / AiSensy", "Bengaluru/Gurugram", "WhatsApp automation", "aisensy.com"],
    ["Interakt (Jio)", "Mumbai", "WhatsApp commerce", "interakt.shop"],
    ["Wati", "Bengaluru", "WhatsApp automation", "wati.io"],
    ["Leena AI", "Gurugram", "HR/agentic AI", "leena.ai"],
    ["Darwinbox", "Hyderabad", "HR SaaS + AI", "darwinbox.com"],
    ["Keka", "Hyderabad", "HR automation", "keka.com"],
    ["Zoho", "Chennai", "SaaS suite + Zia AI", "zoho.com"],
    ["Freshworks", "Chennai", "CX/ITSM SaaS + Freddy AI", "freshworks.com"],
    ["Kissflow", "Chennai", "Low-code workflow", "kissflow.com"],
    ["Whatfix", "Bengaluru", "Digital adoption + AI", "whatfix.com"],
    ["Locus.sh", "Bengaluru", "Logistics AI", "locus.sh"],
    ["Shipsy", "Gurugram", "Supply-chain AI", "shipsy.io"],
    ["FarEye", "Noida", "Delivery logistics AI", "fareye.com"],
    ["Bizom (Mobisy)", "Bengaluru", "Retail/SFA automation", "bizom.com"],
    ["Vymo", "Bengaluru", "Sales engagement AI", "vymo.com"],
    ["Rephrase.ai (Adobe)", "Bengaluru", "Generative video", "rephrase.ai"],
    ["Vizzhy / Setu", "Bengaluru", "Fintech AI/APIs", "setu.co"],
    ["Signzy", "Bengaluru", "BFSI onboarding AI", "signzy.com"],
    ["HyperVerge", "Bengaluru", "KYC/vision AI", "hyperverge.co"],
    ["IDfy", "Mumbai", "Identity + fraud AI", "idfy.com"],
    ["Perfios", "Bengaluru", "Financial data AI", "perfios.com"],
    ["Eela / Recko (Stripe)", "Bengaluru", "Reconciliation AI", "stripe.com"],
    ["EnglishHelper", "Mumbai", "Education AI", "englishhelper.com"],
    ["Embibe (Jio)", "Bengaluru", "EdTech AI", "embibe.com"],
    ["Toplyne", "Bengaluru", "Go-to-market AI", "toplyne.io"],
    ["Avoma", "Pune", "Meeting AI", "avoma.com"],
    ["Rocketium", "Bengaluru", "Creative automation", "rocketium.com"],
    ["Pixis (Pyxis One)", "Bengaluru", "AI marketing infra", "pixis.ai"],
    ["GreyOrange", "Gurugram", "Warehouse robotics AI", "greyorange.com"],
    ["Ati Motors", "Bengaluru", "Industrial autonomy", "ati.motors"],
    ["Detect Technologies", "Chennai", "Industrial vision AI", "detecttechnologies.com"],
    ["Flutura (Accenture)", "Bengaluru", "Industrial IoT AI", "accenture.com"],
    ["Uncountable / Aganitha", "Hyderabad", "R&D / life-sci AI", "aganitha.ai"],
    ["Innoplexus", "Pune", "Life-sciences AI", "innoplexus.com"],
    ["Tredence", "Bengaluru", "Data science consulting", "tredence.com"],
    ["Bristlecone (Mahindra)", "Bengaluru", "Supply-chain AI", "bristlecone.com"],
    ["Brillio", "Bengaluru", "Digital + data/AI", "brillio.com"],
    ["Searce", "Pune", "Cloud + AI engineering", "searce.com"],
    ["CloudCover / NetApp", "Bengaluru", "Cloud + AI", "cloudcover.tech"],
    ["Ascendion", "Chennai/US", "AI-led engineering", "ascendion.com"],
    ["Iauro / Saama", "Pune", "AI engineering + life-sci", "saama.com"],
    ["Affine", "Bengaluru", "AI/analytics consulting", "affine.ai"],
    ["Polestar Solutions", "Noida", "Data analytics", "polestarllp.com"],
    ["MathCo", "Bengaluru", "Enterprise AI/analytics", "themathcompany.com"],
    ["AceVector / Indium", "Chennai", "Data + QA + AI", "indiumsoftware.com"],
    ["Zinnov-backed boutiques", "Multiple", "AI consulting boutiques", "—"],
    ["Sirpi / SculptSoft", "Ahmedabad", "AI/ML dev services", "sculptsoft.com"],
    ["Azilen Technologies", "Ahmedabad", "Product + AI engineering", "azilen.com"],
    ["TatvaSoft", "Ahmedabad", "Custom software + AI", "tatvasoft.com"],
    ["Bacancy Technology", "Ahmedabad", "Dev + AI/ML", "bacancytechnology.com"],
    ["Yudiz Solutions", "Ahmedabad", "Apps + AI", "yudiz.com"],
    ["Inexture / Hyperlink InfoSystem", "Ahmedabad", "AI app dev", "hyperlinkinfosystem.com"],
    ["Simform", "Ahmedabad", "Cloud + AI engineering", "simform.com"],
    ["Radixweb / Elsner", "Ahmedabad", "Software + AI", "radixweb.com"],
    ["Webmyne / Silver Touch", "Vadodara/Ahd", "ERP + AI/RPA", "silvertouch.com"],
    ["Softweb Solutions", "Ahmedabad", "IoT + AI", "softwebsolutions.com"],
    ["Bytes Technolab", "Ahmedabad", "Web/AI dev", "bytestechnolab.com"],
    ["Peerbits / Openxcell", "Ahmedabad", "App + AI dev", "openxcell.com"],
    ["Tridhya Tech", "Ahmedabad", "Digital + AI", "tridhyatech.com"],
    ["Rapidops", "Ahmedabad", "SaaS + AI products", "rapidops.com"],
    ["e-Zest / Cybage", "Pune", "Product engineering + AI", "cybage.com"],
    ["Mastek / Evolutionary Sys", "Mumbai/UAE", "ERP + AI services", "mastek.com"],
    ["Datamatics", "Mumbai", "IPA + analytics", "datamatics.com"],
    ["Newgen Software", "Noida", "Low-code + IDP/AI", "newgensoft.com"],
    ["Intellicus / Kanerika", "Hyderabad", "Data + AI services", "kanerika.com"],
    ["Cinntra / Espire", "Noida", "Digital + AI", "espire.com"],
    ["Orbo.ai / Streamoid", "Mumbai/Bengaluru", "Vision + retail AI", "orbo.ai"],
    ["Lyzr / Dashtoon (GenAI)", "Bengaluru", "Agentic GenAI startups", "lyzr.ai"],
  ];
  const rows = [["#", "Company", "City", "Focus", "Website"]];
  indianFirms.forEach((f, i) => rows.push([String(i + 1), f[0], f[1], f[2], f[3]]));

  return [
    new H.docx.Paragraph({ pageBreakBefore: true, heading: H.docx.HeadingLevel.HEADING_1, children: [H.t("3. Indian Competitor Analysis")] }),
    lead("India has world-class AI delivery talent but a thin domestic-demand engine. Most strong players chase US/EU enterprise revenue — leaving the Indian SME, regional and vernacular markets wide open."),

    p("Per your guidance, we profile the most relevant players in depth and provide a ~100-name reference directory below. Treat private-company financials as best-available estimates [refs 17,19–22]."),

    h2("3.1 Deep Profiles — Indian Leaders"),
    table([2200, 7160], [
      ["Fractal Analytics", "Mumbai · 2000 · founders Srikanth Velamakanni & Pranay Agrawal · ~6,700 staff · ~$330 M ARR, ~$2.4 B valuation, IPO-bound. USP: enterprise-grade AI + behavioural science for global CPG/BFSI. Tech: cloud, ML, GenAI. Weakness: minimal Indian/SME demand — ~near-entirely export-led [17]."],
      ["Yellow.ai", "Bengaluru · 2016 · founders Raghu Ravinutala et al. · ~1,000 staff · conversational + voice AI across 135+ languages. USP: enterprise CX automation; strong in Asia/ME. Weakness: crowded conversational-AI market, margin pressure."],
      ["Qure.ai", "Mumbai · 2016 · radiology AI (chest X-ray, CT, stroke) · FDA/CE cleared, deployed in 90+ countries. USP: regulatory-cleared clinical AI. A model for vertical, outcome-led AI."],
      ["Zoho / Freshworks", "Chennai · global SaaS leaders with embedded AI (Zia, Freddy). USP: full SMB software suites at low cost. They prove the Indian SMB-SaaS playbook — but leave services/customisation to partners."],
      ["Tredence / Tiger / Quantiphi / MathCo", "Bengaluru/Chennai · data-science & applied-AI consultancies, $150–350 M scale, US-centric. USP: deep analytics talent. Weakness: enterprise-only; little SME productisation."],
    ], { fontSize: 16 }),

    h2("3.2 Ahmedabad & Gujarat — Your Home-Turf Cluster"),
    p("Gujarat (Ahmedabad, Gandhinagar GIFT City, Vadodara, Surat, Rajkot) hosts a dense services-IT cluster — Azilen, TatvaSoft, Bacancy, Simform, Openxcell, Silver Touch, Softweb, Radixweb, Yudiz, Hyperlink InfoSystem, Rapidops, SculptSoft. Most are export-oriented custom-software / app shops now bolting on 'AI/ML' as a service line. Few have a sharp, productised, outcome-led AI proposition aimed at Gujarat's own manufacturing, textile, pharma, chemicals, agro/food and export economy. That local-market + vernacular gap is a concrete opening for a focused new division."),

    h2("3.3 Fast-Growing AI Startups (India)"),
    bullet("Conversational/Voice: Yellow.ai, Gupshup, Skit.ai, Observe.AI, Uniphore — maturing fast; CX automation mainstream."),
    bullet("Vertical AI: Qure.ai (radiology), Niramai/SigTuple (health), Signzy/HyperVerge/IDfy (BFSI onboarding), GreyOrange/Ati Motors (warehouse/industrial robotics)."),
    bullet("Agentic GenAI (2024–26 wave): Lyzr, Leena AI, Toplyne, Pixis, Rephrase.ai — building reusable agent/automation IP."),
    bullet("SMB enablement: AiSensy, Wati, Interakt, Bizom — productised WhatsApp/retail automation; proof that SME automation sells at volume."),

    h2("3.4 Under-Served Markets & Service Gaps in India"),
    callout("Gaps competitors are NOT solving", [
      "SME/MSME automation at affordable, productised price points (63 M MSMEs, low AI adoption) [14].",
      "Vernacular / regional-language AI for tier-2/3 businesses and their customers.",
      "Industry-specific 'done-for-you' solutions for textile, pharma, chemicals, agro/food, gems & jewellery, exports — Gujarat's core.",
      "Export documentation, compliance and trade automation (huge in Gujarat/Surat/Mumbai).",
      "End-to-end 'AI ops' for clinics, schools, dealerships, real-estate and D2C brands — too small for the majors.",
      "AI governance, data-readiness and pilot-rescue for mid-market firms with stalled projects.",
    ]),

    h2("3.5 Regional Opportunity Snapshot"),
    table([1750, 2500, 5110], [
      ["City / Region", "Economic base", "Best opening for you"],
      ["Ahmedabad / Gujarat", "Manufacturing, textile, pharma, chemicals, agro/food, exports, GIFT-City fintech", "Local + vernacular productised AI/automation; export & compliance automation; lowest competition vs depth of demand"],
      ["Mumbai", "BFSI, media, pharma HQs, D2C", "BFSI process automation, marketing AI, analytics — high deal value, high competition"],
      ["Bengaluru", "Tech, startups, GCCs", "AI engineering talent + partnerships; saturated for selling, strong for hiring"],
      ["Hyderabad", "Pharma, GCCs, govt-tech", "Life-sciences & data AI; pro-business policy"],
      ["Pune", "Auto, manufacturing, IT", "Industry-4.0 / manufacturing AI, computer vision QC"],
      ["Delhi NCR (Gurugram/Noida)", "Corporates, e-commerce, logistics, govt", "Logistics/HR/CX automation; large enterprise + govt access"],
    ], { fontSize: 17 }),

    h2("3.6 Indian Competitor Reference Directory (~100)"),
    p("A scan map of Indian firms touching AI/automation/IT-transformation — for partnership, talent and positioning intelligence. Inclusion is not an endorsement; financials omitted where unreliable."),
    table([520, 2640, 1900, 2400, 1900], rows, { fontSize: 14 }),
    source("Company websites, Crunchbase, Inc42, YourStory, Tracxn, NASSCOM (2024–2026). Private financials are estimates. Full citations in References."),
  ];
}

module.exports = { section1, section2, section3 };
